//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUC_VU
    {
        public CHUC_VU()
        {
            this.GIU_CHUC_VU = new HashSet<GIU_CHUC_VU>();
            this.QUYEN_SD = new HashSet<QUYEN_SD>();
        }
    
        public int MA_CHUC_VU { get; set; }
        public string TEN_CHUC_VU { get; set; }
    
        public virtual ICollection<GIU_CHUC_VU> GIU_CHUC_VU { get; set; }
        public virtual ICollection<QUYEN_SD> QUYEN_SD { get; set; }
    }
}
