//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUNG_CAP_SACH
    {
        public int MA_NCC { get; set; }
        public int MA_SACH { get; set; }
        public Nullable<System.DateTime> THOI_GIAN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual CUON_SACH CUON_SACH { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
    }
}
