//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUON_SACH
    {
        public CUON_SACH()
        {
            this.PHATs = new HashSet<PHAT>();
            this.SACH_MUON = new HashSet<SACH_MUON>();
            this.CUNG_CAP_SACH = new HashSet<CUNG_CAP_SACH>();
        }
    
        public int MA_SACH { get; set; }
        public int MA_DAU_SACH { get; set; }
        public Nullable<int> GIA_SACH { get; set; }
        public string TEN_SACH { get; set; }
        public Nullable<int> SO_TRANG { get; set; }
        public string GHI_CHU_SACH { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<int> NAM_XUAT_BAN { get; set; }
        public string MA_VACH { get; set; }
        public Nullable<int> TAI_BAN { get; set; }
    
        public virtual DAU_SACH DAU_SACH { get; set; }
        public virtual ICollection<PHAT> PHATs { get; set; }
        public virtual ICollection<SACH_MUON> SACH_MUON { get; set; }
        public virtual ICollection<CUNG_CAP_SACH> CUNG_CAP_SACH { get; set; }
    }
}
