//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOI_TUONG
    {
        public DOI_TUONG()
        {
            this.DOC_GIA = new HashSet<DOC_GIA>();
        }
    
        public int MA_DOI_TUONG { get; set; }
        public string TEN_DOI_TUONG { get; set; }
    
        public virtual ICollection<DOC_GIA> DOC_GIA { get; set; }
    }
}
