//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIU_CHUC_VU
    {
        public int MA_NHAN_VIEN { get; set; }
        public int MA_CHUC_VU { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC { get; set; }
    
        public virtual CHUC_VU CHUC_VU { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
