//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KE_SACH
    {
        public KE_SACH()
        {
            this.DAU_SACH = new HashSet<DAU_SACH>();
        }
    
        public int MA_KE_SACH { get; set; }
        public int MA_KHU_VUC { get; set; }
        public string TEN_KE_SACH { get; set; }
    
        public virtual KHU_VUC KHU_VUC { get; set; }
        public virtual ICollection<DAU_SACH> DAU_SACH { get; set; }
    }
}
