//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHU_VUC
    {
        public KHU_VUC()
        {
            this.KE_SACH = new HashSet<KE_SACH>();
        }
    
        public int MA_KHU_VUC { get; set; }
        public string TEN_KHU_VUC { get; set; }
    
        public virtual ICollection<KE_SACH> KE_SACH { get; set; }
    }
}
