//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LY_DO_PHAT
    {
        public LY_DO_PHAT()
        {
            this.PHATs = new HashSet<PHAT>();
        }
    
        public int MA_LY_DO { get; set; }
        public string LY_DO_PHAT1 { get; set; }
        public Nullable<int> SO_TIEN_PHAT { get; set; }
        public string GHI_CHU_PHAT { get; set; }
    
        public virtual ICollection<PHAT> PHATs { get; set; }
    }
}
