//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHA_CUNG_CAP
    {
        public NHA_CUNG_CAP()
        {
            this.CUNG_CAP_SACH = new HashSet<CUNG_CAP_SACH>();
        }
    
        public int MA_NCC { get; set; }
        public string TEN_NCC { get; set; }
    
        public virtual ICollection<CUNG_CAP_SACH> CUNG_CAP_SACH { get; set; }
    }
}
