//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThuVienEntities1 : DbContext
    {
        public QuanLyThuVienEntities1()
            : base("name=QuanLyThuVienEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHINH_SACH_LUU_THONG> CHINH_SACH_LUU_THONG { get; set; }
        public DbSet<CHUC_VU> CHUC_VU { get; set; }
        public DbSet<CUON_SACH> CUON_SACH { get; set; }
        public DbSet<DAU_SACH> DAU_SACH { get; set; }
        public DbSet<DOC_GIA> DOC_GIA { get; set; }
        public DbSet<DOI_TUONG> DOI_TUONG { get; set; }
        public DbSet<GIU_CHUC_VU> GIU_CHUC_VU { get; set; }
        public DbSet<KE_SACH> KE_SACH { get; set; }
        public DbSet<KHU_VUC> KHU_VUC { get; set; }
        public DbSet<LOAI_SACH> LOAI_SACH { get; set; }
        public DbSet<LY_DO_PHAT> LY_DO_PHAT { get; set; }
        public DbSet<MUON_TRA_SACH> MUON_TRA_SACH { get; set; }
        public DbSet<NGON_NGU> NGON_NGU { get; set; }
        public DbSet<NHA_XUAT_BAN> NHA_XUAT_BAN { get; set; }
        public DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public DbSet<PHAT> PHATs { get; set; }
        public DbSet<TAC_GIA> TAC_GIA { get; set; }
        public DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public DbSet<SACH_MUON> SACH_MUON { get; set; }
        public DbSet<CUNG_CAP_SACH> CUNG_CAP_SACH { get; set; }
        public DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public DbSet<QUYEN> QUYENs { get; set; }
        public DbSet<QUYEN_SD> QUYEN_SD { get; set; }
    }
}
