//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN_SD
    {
        public int MA_QUYEN { get; set; }
        public int MA_CHUC_VU { get; set; }
        public string MENU { get; set; }
    
        public virtual CHUC_VU CHUC_VU { get; set; }
        public virtual QUYEN QUYEN { get; set; }
    }
}
