//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN
    {
        public QUYEN()
        {
            this.QUYEN_SD = new HashSet<QUYEN_SD>();
        }
    
        public int MA_QUYEN { get; set; }
        public string TEN_QUYEN { get; set; }
    
        public virtual ICollection<QUYEN_SD> QUYEN_SD { get; set; }
    }
}
