//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH_MUON
    {
        public int MA_SACH { get; set; }
        public int MA_MUON_TRA { get; set; }
        public Nullable<System.DateTime> NGAY_PHAI_TRA { get; set; }
        public Nullable<bool> DA_TRA { get; set; }
        public Nullable<System.DateTime> THOI_GIAN_TRA { get; set; }
        public Nullable<int> GIA_HAN { get; set; }
    
        public virtual CUON_SACH CUON_SACH { get; set; }
        public virtual MUON_TRA_SACH MUON_TRA_SACH { get; set; }
    }
}
