//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoHoiCuoiCung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_KHOAN
    {
        public int MA_TAI_KHOAN { get; set; }
        public Nullable<int> MA_NHAN_VIEN { get; set; }
        public Nullable<int> MA_DOC_GIA { get; set; }
        public string TEN_TAI_KHOAN { get; set; }
        public string MAT_KHAU { get; set; }
    
        public virtual DOC_GIA DOC_GIA { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
